# Configuration file for SkyBlockUI
# Made by TheRealKizu (https://github.com/TheRealKizu)

# Options:
# True - If you want to use RedSkyBlock by RedCraftGH.
# False - If you want to use SkyBlock by GiantQuartz.
is-redskyblock: false