name: SkyBlockUI
main: TheRealKizu\SkyBlockUI\Loader
version: 1.0.4
api: [3.0.0]
author: TheRealKizu
description: SkyBlockUI plugin for PocketMine-MP
softdepend:
  - SkyBlock
  - RedSkyBlock

#Extra
website: https://therealkizu.tk
