name: SkyBlockUI
main: TheRealKizu\SkyBlockUI\Core
version: 1.0.3
api: [3.0.0]
author: TheRealKizu
description: SkyBlockUI plugin for PocketMine-MP
depend:
  - SkyBlock

#Extra
website: https://therealkizu.tk
